2018-03-27 12:24:57 testmycase.py[line:36] WARNING : test2----33
